name: extended_dart_lints
description: Lints and rules that go beyond Flutter's own recommendations
version: 0.0.1
repository: https://github.com/bjoernahrens/extended_dart_lints

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter_lints: ^2.0.1

cider:
  link_template:
    tag: https://github.com/bjoernahrens/extended_dart_lints/releases/tag/%tag% # initial release link template
    diff: https://github.com/bjoernahrens/extended_dart_lints/compare/%from%...%to%
