name: galactic_lints
description: A very opinionated Collection of Linter Rules for Flutter and Dart that go beyond.
version: 1.0.0
repository: https://github.com/bjoernahrens/galactic_lints

environment:
  sdk: ^3.0.0

dependencies:
  flutter_lints: ">=3.0.1 <5.0.0"

cider:
  link_template:
    tag: https://github.com/bjoernahrens/galactic_lints/releases/tag/%tag%
    diff: https://github.com/bjoernahrens/galactic_lints/compare/%from%...%to%

topics:
  - lints
  - analysis
