name: extended_dart_lints
description: Lints and rules that go beyond Flutter's own recommendations
version: 1.0.0
repository: https://github.com/bjoernahrens/extended_dart_lints

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter_lints: ^2.0.1
