version: "3"

tasks:
  release:
    cmds:
      - cider release
      - git add CHANGELOG.md
      - 'git commit -m "chore: update CHANGELOG for v$(cider version)"'
      - git tag -a "$(cider version)" -m "$(cider version)"
  publish:
    cmds:
      - dart pub publish
