version: "3"

tasks:
  release:
    cmds:
      - cider release
      - git add CHANGELOG.md
      - 'git commit -m "chore: update CHANGELOG for v$(cider version)"'
      - git tag -a "$(cider version)" -m "$(cider version)"
      - git push
      - gh release create "v$(cider version)" --notes-file CHANGELOG.md --verify-tag
  publish:
    cmds:
      - dart pub publish
